name: Install Git and Required Libraries
description: Require installation of Git 2.26.2.
inputs:
  git-version:
    required: false
    default: 2.26.2
runs:
  using: "composite"

  steps:
  - name: Workaround for archived files in debian image
    shell: bash
    run: |
        cat /etc/apt/sources.list.d/debian-azure.list
        echo "deb http://archive.debian.org/debian stretch main contrib non-free 
        deb http://archive.debian.org/debian-security stretch/updates main contrib non-free
        deb http://archive.debian.org/debian stretch-backports main contrib non-free" > /etc/apt/sources.list.d/debian-azure.list
  - name: Install Git and Required Libraries
    shell: bash
    run: |
        apt-get update
        apt install -y libz-dev libssl-dev libcurl4-gnutls-dev libexpat1-dev gettext cmake clang clang-format clang-tidy lldb libcppunit-dev libicu-dev gcc g++
        curl -o git.tar.gz http://mirrors.edge.kernel.org/pub/software/scm/git/git-${{ inputs.git-version }}.tar.gz
        tar -zxf git.tar.gz
        cd git-*
        make prefix=/usr/local all -j$(nproc)
        make prefix=/usr/local install

  