class Columns:
    PRODUCT_ID = "PRODUCT_ID"
    LOCATION_ID = "LOCATION_ID"
    DEMAND = "DEMAND_QTY"
    BOM_ID = "BOM_ID"
    BOM_LOCATION_ID = "BOM_LOCATION_ID"
    BOM_COMPONENT_ID = "BOM_COMPONENT"
    BOM_PRODUCT_ID = "MANUFACTURED_PRODUCT"