name: PYCPP Build Pipeline

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref_name != 'main' && github.ref_name || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim
      env:
        NODE_ENV: development
      ports:
        - 80
      options: --cpus 2

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          python3.10 -m venv venvlyric
          . venvlyric/bin/activate
          python3.10 -m pip install --use-deprecated=legacy-resolver --force-reinstall -r requirements.txt
          python3.10 -m pip freeze
        shell: bash

      - name: Install make and g++
        run: |
          apt-get update && \
          apt-get -y install g++ cmake  && \
          rm -rf /var/lib/apt/lists/*
        shell: bash

      - name: Build binaries
        env:
          GCC_VERSION: 6
        run: |
          . venvlyric/bin/activate
          rm -rf cpp/build
          cmake -S cpp -B cpp/build -D CMAKE_BUILD_TYPE=Debug
          cmake --build cpp/build -j
          mkdir -p mylyric/lib/
          cp cpp/build/lyric_module.* mylyric/lib/
          pip install .
          python mylyric/script.py
          pytest tests/
        shell: bash



